instance_type = "t2.micro"
key_name      = "Mentra" #change this to your key-pair name
# ami_id            = "ami-0f918f7e67a3323f0"
stage             = "dev"
shutdown_minutes  = 30
s3_bucket_name    = "techeazy-logs-unique123ss" # Change this!
aws_region        = "ap-south-1"
repo_url          = "https://github.com/techeazy-consulting/techeazy-devops"
verifier_lifetime = 25
